version: "3.5"

services:
  api-invgate-facade:
    restart: always
    container_name: api-invgate-facade
    env_file: ./api/.env
    build: 
      context: ./api/.
      dockerfile: Dockerfile
    command: yarn watch 
    image: api-invgate-facade
    depends_on:
      - api-invgate-cache
    networks:
      api-invgate-backend-network:
        aliases:
          - api-invgate-facade

  api-invgate-cache:
    restart: always
    container_name: api-invgate-cache
    image: redis:buster
    networks:
      api-invgate-backend-network:
        aliases:
          - api-invgate-cache

  api-invgate-doc:
    image: swaggerapi/swagger-ui
    container_name: api-invgate-doc
    volumes:
      - ./api/doc/invgate.api.v2.openapi.json:/invgate.api.v2.openapi.json
    environment:
      SWAGGER_JSON: /invgate.api.v2.openapi.json
    networks:
      api-invgate-backend-network:
        aliases:
          - api-invgate-doc


  api-invgate-gateway:
    image: nginx:alpine
    container_name: api-invgate-gateway
    restart: always
    volumes:
      - ./api/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - api-invgate-backend-network
    depends_on:
      - api-invgate-facade
      - api-invgate-doc

  front-invgate:
    restart: always
    container_name: front-invgate
    build: 
      context: ./front/.
      dockerfile: Dockerfile
    command: yarn start
    image: front-invgate
    networks:
      - api-invgate-backend-network
    depends_on:
      - api-invgate-gateway

networks:
  api-invgate-backend-network:
    name: "api-invgate-backend-network"
    driver: "bridge"
 