export const ASYNC_AGENT_START = 'ASYNC_AGENT_START'; 
export const ASYNC_AGENT_END ='ASYNC_AGENT_END';
export const ASYNC_AGENT_ERROR = 'ASYNC_AGENT_ERROR';
export const ASYNC_PROCESS_START = 'ASYNC_PROCESS_START';
export const ASYNC_PROCESS_END = 'ASYNC_PROCESS_END';
